### DISCUSSION TITLE
INFO level logging messages in flox

### DISCUSSION THREAD

**Discussion by douglatornell** [pydata/xarray#9148] [General] [answered]
Apologies if this is not the correct place for this, but I couldn't find a discussion forum for flox.

I recently updated to xarray 2024.06.0 and flox 0.9.8 in a production environment that includes processes that resample DataArrays many times a day. The log files now include lots of messages like:

> 2024-06-19 03:08:44,005 INFO [get_onc_ctd] Entering _validate_reindex: reindex is None
> 2024-06-19 03:08:44,007 INFO [get_onc_ctd] Leaving _validate_reindex: method = None, returning None
> 2024-06-19 03:08:44,009 INFO [get_onc_ctd] _choose_engine: Choosing 'flox'

After reviewing the flox docs and code, it is not clear to me that I should be changing anything in my resample() calls. 

In my opinion, messages like those should be at the DEBUG level, not INFO. If you would like, @dcherian , I would be happy to open a PR to review and adjust logging message levels in flox. I am also happy to accept that my opinion is unpopular and the logging level was set to INFO for reasons I'm unaware of. In that case, I can add a logger/handler to our logging setup to filter out those (uninteresting to me) messages.

**Comment by dcherian** [comment, marked as answer]
oops my bad. Yes a PR switching these to DEBUG would be welcome. 

Out of curiousity , how are you configuring `logging`? I assumed one would have to configure logging for flox specifically to see these messages, but looks like I am wrong.

**Reply by douglatornell** [reply]
> oops my bad. Yes a PR switching these to DEBUG would be welcome.

No problem! I'm glad I asked. It might be next week before I get the PR ready.

> Out of curiousity , how are you configuring logging? I assumed one would have to configure logging for flox specifically to see these messages, but looks like I am wrong.

I've got the root logger level set to DEBUG and I use handlers and loggers to "direct traffic" from there. So, I have INFO above going to one file, and DEBUG to another. In YAML it looks like:
```yaml
    disable_existing_loggers: False
    formatters:
      simple:
        format: '%(asctime)s %(levelname)s [%(logger_name)s] %(message)s'
    handlers:
      info_text:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: $(NOWCAST.ENV.NOWCAST_LOGS)/nowcast.log
        backupCount: 7
      debug_text:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: $(NOWCAST.ENV.NOWCAST_LOGS)/nowcast.debug.log
        backupCount: 7
    root:
      level: DEBUG
      handlers:
       - info_text
       - debug_text
```
Then, if there is a "noisy" dependency that I want to filter so that I don't see its DEBUG and INFO messages, I add a logger for it like:
```yaml
loggers:
      PIL:
        # Python Imaging Library (aka pillow) used by figure modules
        qualname: PIL
        level: WARNING
        formatter: simple
```
