### ISSUE TITLE
opendap access fails only in ubuntu machines

### ISSUE THREAD

**Issue by aragong** [pydata/xarray#7773]
### What happened?

I am having errors on opendap access (any of them):
```python
import xarray as xr

url = "https://erddap.emodnet.eu/erddap/griddap/bathymetry_2022"
url = "https://ihthredds.ihcantabria.com/thredds/dodsC/Bathymetry/Global/Gebco_2020.nc"

ds = xr.open_dataset(url)
```

The point is that only ocurrs when i deploy and test the code on an ubuntu-latest machine using (pyenv+pip), see summary of the action:
![image](https://user-images.githubusercontent.com/48764870/233387686-e266025f-2b80-4d08-a40f-3d0795051f07.png)

my dependencies are defined on pyproject.toml file like this:
```toml
dependencies = [
"geopandas",
"xarray",
"netCDF4",
"h5netcdf",
"scipy",
"pydap",
"zarr",
"fsspec",
"cftime",
"pooch",
"dask[complete]",
"ipykernel",
"matplotlib",
"owslib",
"shapely",
"geojson",
"pytest>=7",
"lxml",
"python-dotenv",
]
```
However, If I use conda on wsl unbuntu 20.04 LTS with this environment.yml, works fine:

```yaml
name: pyteseo-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - xarray
  - dask
  - netcdf4
  - bottleneck
  - ipykernel
  - matplotlib
  - geopandas
  - owslib
  - shapely
  - geojson
  - pytest>=7
  - coverage
  - flit
  - black
  - sphinx
  - myst-nb
  - sphinx-autoapi
  - sphinx_rtd_theme
  - pre_commit
  - flake8
  - pydap
  - lxml
  - scipy
  - python-dotenv
```

Public repository here: [pyTESEO](https://github.com/IHCantabria/pyteseo)

### What did you expect to happen?

I expect to pass all tests

### Minimal Complete Verifiable Example

```Python
import xarray as xr

url = "https://erddap.emodnet.eu/erddap/griddap/bathymetry_2022"
url = "https://ihthredds.ihcantabria.com/thredds/dodsC/Bathymetry/Global/Gebco_2020.nc"

ds = xr.open_dataset(url)
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [ ] Complete example — the example is self-contained, including all data and the text of any traceback.
- [ ] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [ ] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Environment

<details>

</details>
